AWSTemplateFormatVersion: 2010-09-09
Description: Managed Stack for AWS SAM CLI
Metadata:
  SamCliInfo:
    version: 1.50.0
    installationId: bb7d6900-2633-4a88-9fac-c89727e637e4
Outputs:
  SourceBucket:
    Value: !Ref SamCliSourceBucket
Resources:
  SamCliSourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: 'true'
        BlockPublicAcls: 'true'
        IgnorePublicAcls: 'true'
        RestrictPublicBuckets: 'true'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: ManagedStackSource
          Value: AwsSamCli
  SamCliSourceBucketBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SamCliSourceBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join 
              - ''
              - - 'arn:'
                - !Ref 'AWS::Partition'
                - ':s3:::'
                - !Ref SamCliSourceBucket
                - /*
            Principal:
              Service: serverlessrepo.amazonaws.com
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'
          - Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':s3:::'
                  - !Ref SamCliSourceBucket
              - !Join 
                - ''
                - - 'arn:'
                  - !Ref 'AWS::Partition'
                  - ':s3:::'
                  - !Ref SamCliSourceBucket
                  - /*
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
