AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  apollo-lambda-sam

  Sample SAM Template for apollo-lambda-sam
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6
    Tracing: Active

Resources:
  ApolloServerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: apollo-lambda/
      Handler: index.graphqlHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE

      Policies:
        Version: '2012-10-17'
        Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - rds-data:ExecuteStatement
                    - secretsmanager:*
                    - lambda:InvokeFunction
                    - lambda:InvokeAsync
                    - logs:CreateLogGroup
                  Resource:
                    - "arn:aws:lambda:us-west-2:YOUR_ACCOUNT:function:API_list"
                    - "arn:aws:logs:us-west-2:YOUR_ACCOUNT:log-group:/aws/lambda/apollolambdatest-dev*:*"
                    - "arn:aws:rds:us-west-2:YOUR_ACCOUNT:cluster:pcmt-25-serverless"
                    - "arn:aws:secretsmanager:us-west-2:YOUR_ACCOUNT:secret:rds-db-credentials/cluster-RV3Y7OJVZRC5XYJBOYI2CY7CJ4/admin2-MQASTx"
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - "arn:aws:logs:us-west-2:YOUR_ACCOUNT:log-group:/aws/lambda/apollolambdatest-dev*:*:*"
                - Effect: Allow
                  Action:
                    - secretsmanager:GetRandomPassword
                    - secretsmanager:ListSecrets
                  Resource: "*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyFunctionUrlEndpoint:
      Description: "My Lambda Function URL Endpoint"
      Value:
        Fn::GetAtt: ApolloServerFunctionUrl.FunctionUrl
  ApolloServerFunction:
    Description: "Apollo Server Lambda Function ARN"
    Value: !GetAtt ApolloServerFunction.Arn
  ApolloServerFunctionIamRole:
    Description: "IAM Role created for Apollo Server function"
    Value: !GetAtt ApolloServerFunctionRole.Arn
