# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: apollolambdatest
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2


functions:
  apollo-server-function:
    role: apollomyCustRole0
    handler: index.graphqlHandler
    url:
      # Allow CORS for all requests from any origin
      cors: true

resources:
  Resources:
    apollomyCustRole0:
      Type: AWS::IAM::Role
      Properties:
        Path: /my/cust/path/
        RoleName: apollo-MyCustRole0
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: apollo-myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - rds-data:ExecuteStatement
                    - secretsmanager:*
                    - lambda:InvokeFunction
                    - lambda:InvokeAsync
                    - logs:CreateLogGroup
                  Resource:
                    - "arn:aws:lambda:us-west-2:YOUR_ACCOUNT:function:API_list"
                    - "arn:aws:logs:us-west-2:YOUR_ACCOUNT:log-group:/aws/lambda/apollolambdatest-dev*:*"
                    - "arn:aws:rds:us-west-2:YOUR_ACCOUNT:cluster:pcmt-25-serverless"
                    - "arn:aws:secretsmanager:us-west-2:YOUR_ACCOUNT:secret:rds-db-credentials/cluster-RV3Y7OJVZRC5XYJBOYI2CY7CJ4/admin2-MQASTx"
                - Effect: Allow
                  Action:
                    - logs:PutLogEvents
                  Resource:
                    - "arn:aws:logs:us-west-2:YOUR_ACCOUNT:log-group:/aws/lambda/apollolambdatest-dev*:*:*"
                - Effect: Allow
                  Action:
                    - secretsmanager:GetRandomPassword
                    - secretsmanager:ListSecrets
                  Resource: "*"